<template>
    <div>
        모임방페이지
        <!-- <컴포넌트></컴포넌트> -->
    </div>
</template>

<script>
// import 컴포넌트이름 from "../컴포넌트경로"
export default {
    data(){
        return{
            //데이터key:value,데이터key2:value
        }
    },
    components:{
        // 컴포넌트이름
        headerComponent,
        copyright,
        movetop
    },
    methods:{
        // 메서드이름(){}
    }
}
</script>



<style scoped>

</style>
